# Generated by Django 4.2.2 on 2025-11-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_chapter_book_users_youtubelink_tableofcontententry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='book_voices/'),
        ),
    ]
