# Generated by Django 4.2.2 on 2025-11-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Rich text content in JSON format (TipTap/ProseMirror)', null=True),
        ),
    ]
