# Generated by Django 4.2.2 on 2025-11-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_add_book_content_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='markdown_content',
            field=models.TextField(blank=True, help_text='Markdown content that will be converted to HTML with TOC', null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='markdown_content',
            field=models.TextField(blank=True, help_text='Markdown content for chapter', null=True),
        ),
    ]
