# Generated by Django 4.2.2 on 2025-11-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_markdown_content_chapter_markdown_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableofcontententry',
            name='anchor_id',
            field=models.CharField(blank=True, help_text='ID attribute for linking to content sections', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tableofcontententry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='books.tableofcontententry'),
        ),
        migrations.AlterUniqueTogether(
            name='tableofcontententry',
            unique_together={('book', 'order', 'parent')},
        ),
    ]
