# Generated by Django 4.2.2 on 2025-11-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_add_parent_to_toc_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='toc_position',
            field=models.CharField(choices=[('sidebar', 'Sidebar (Left)'), ('top', 'Top of Page'), ('bottom', 'Bottom of Page'), ('none', 'Hidden')], default='sidebar', help_text='Where to display the Table of Contents', max_length=20),
        ),
    ]
