# Generated by Django 4.2.2 on 2025-11-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_paid',
        ),
    ]
